name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 4
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=4
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=4
        pnpm exec nx affected --target=test --parallel=4 --ci --code-coverage
        pnpm exec nx affected --target=build --parallel=4
        pnpm exec nx affected --target=e2e --parallel=4

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 4
